import {useEffect,useRef,useState} from 'react';
import {useLocalAccess} from '../../../core/local/LocalAccess';
import {localClient,localErrorMessage,useLocalSession} from '../../../core/local/useLocalSession';
import type {StaffMember} from '../../../core/local/localClient.mjs';
export default function LocalStaff(){
 const token=useLocalSession(s=>s.token),session=useLocalSession(s=>s.session);const {capabilities}=useLocalAccess();
 const [rows,setRows]=useState<StaffMember[]>([]),[name,setName]=useState(''),[role,setRole]=useState('employee'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [pending,setPending]=useState<{operation_id:string;identity_id:string;name:string;role:string}|null>(null);const latch=useRef(false);
 const key=`titan-staff-pending:${session?.tenant_id}:${session?.store_id}:${session?.device_id}:${session?.identity_id}`;
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const value=JSON.parse(raw);if(!value || !['operation_id','identity_id','name','role'].every(k=>typeof value[k]==='string') || Object.keys(value).length!==4)throw new Error();setPending(value);setName(value.name);setRole(value.role);}}catch{setError('Não foi possível conferir o cadastro pendente. Não envie outro cadastro antes da conferência.');setPending({operation_id:'',identity_id:'',name:'',role:''});}},[key]);
 useEffect(()=>{if(!token)return;let live=true;localClient.staff(token).then(v=>{if(live)setRows(v);}).catch(e=>{if(live)setError(localErrorMessage(e));});return()=>{live=false;};},[token,revision]);
 const roles=capabilities?.role==='owner'?['employee','cashier','stock','production','accountant','manager','supplier']:['employee','cashier','stock'];
 const labels:Record<string,string>={owner:'Dono',employee:'Funcionário — sem gestão de outras áreas',cashier:'Operador de caixa',stock:'Estoque',production:'Produção',accountant:'Contador',manager:'Gerente',supplier:'Fornecedor'};
 async function save(){
  if(latch.current || !token || capabilities?.license.state!=='active')return;latch.current=true;setBusy(true);setError('');setMessage('');
  const input=pending || {operation_id:crypto.randomUUID(),identity_id:crypto.randomUUID(),name:name.trim(),role};
  try {
   if(!input.operation_id || !input.identity_id)throw new Error('Cadastro pendente inválido. Solicite conferência técnica.');
   if(new TextEncoder().encode(password).length<12 || new TextEncoder().encode(password).length>72)throw new Error('A senha precisa ter entre 12 e 72 bytes.');
   if(!navigator.locks)throw new Error('Use navegador com proteção entre abas em localhost.');
   await navigator.locks.request(key,{ifAvailable:true},async lock=>{if(!lock)throw new Error('Outra aba está cadastrando um funcionário.');const existing=localStorage.getItem(key);if(existing && existing!==JSON.stringify(input))throw new Error('Há outro cadastro pendente. Atualize a página.');localStorage.setItem(key,JSON.stringify(input));setPending(input);const result=await localClient.createStaff(token,{...input,password});localStorage.removeItem(key);setPending(null);setName('');setMessage(`Funcionário cadastrado. ID para login local: ${result.identity_id}`);setRevision(v=>v+1);});
  }catch(e){setError(e instanceof Error?e.message:localErrorMessage(e));}finally{setPassword('');setBusy(false);latch.current=false;}
 }
 return <main className="brand-app-content"><p className="brand-eyebrow">RH · ACESSO AUTORIZADO</p><h1>Funcionários</h1><p className="brand-state">Cadastro nesta loja. Não concede módulos que a empresa não contratou.</p>{error && <p role="alert" className="brand-message error">{error}</p>}{message && <p role="status" className="brand-message">{message}</p>}<section className="brand-panel"><h2>{pending?'Conferir cadastro pendente':'Cadastrar funcionário'}</h2><p className="brand-state">A senha fica apenas em memória durante o envio. Na perda de resposta, digite a mesma senha e reenvie o cadastro original.</p><form className="catalog-form" onSubmit={e=>{e.preventDefault();void save();}}><label>Nome<input required maxLength={255} value={name} disabled={busy || !!pending} onChange={e=>setName(e.target.value)}/></label><label>Perfil<select value={role} disabled={busy || !!pending} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><label className="catalog-wide">Senha de acesso local<input required type="password" autoComplete="new-password" value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><button className="brand-small-primary catalog-wide" disabled={busy || capabilities?.license.state!=='active'}>{busy?'Registrando…':pending?'Reenviar cadastro original':'Cadastrar funcionário'}</button></form><p className="brand-message">A delegação específica de poderes ao RH e as permissões individuais configuráveis são a próxima integração. Nesta etapa valem os perfis existentes; não é possível criar outro dono.</p></section><section className="brand-panel" style={{marginTop:20}}><h2>Funcionários desta loja — até 100 registros</h2><div className="brand-table-scroll"><table className="brand-table"><thead><tr><th>Nome</th><th>Perfil</th><th>ID de login</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.identity_id}><td>{r.name}</td><td>{labels[r.role] || r.role}</td><td>{r.identity_id}</td><td>{r.status}</td></tr>)}</tbody></table></div></section></main>;
}
