import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useLocalAccess} from '../../../core/local/LocalAccess';
import {createReceivingRead} from '../../../core/local/receivingRead.mjs';
import type {PurchaseSearch,ReceivingHistory,HistoryEntry} from '../../../core/local/receivingRead.mjs';
import {exactQuantity as q} from '../../../core/local/operationsRead.mjs';
import {useReadTask,ReadState,ReadSection,Pages} from '../../production/pages/readPanel';
const client=createReceivingRead();
const statuses:Record<string,string>={not_authorized:'Não autorizado',authorized:'Autorizado',partially_received:'Recebido parcialmente',received:'Recebido integralmente'};
function Entry({entry:e}:{entry:HistoryEntry}){
 const value=e.kind==='received'?e.receipt:e.kind==='rejected'?e.rejection:e.void;
 return <details><summary>{e.kind==='received'?'Recebimento':e.kind==='rejected'?'Recusa integral':'Anulação por erro de lançamento'} · {e.created_at}</summary>
 <p className="operation-id">Registro: {e.id}<br/>Operador: {value.actor_id}<br/>Motivo: {value.reason}</p>
 {e.kind==='received'&&<><p>Entrega: {e.receipt.delivery_reference} · Local: {e.receipt.location_id}</p><p>Entregue: {q(e.receipt.delivered_milli)} {value.unit} · Aceito original: {q(e.receipt.accepted_milli)} {value.unit} · Recusado parcial: {q(e.receipt.delivered_milli-e.receipt.accepted_milli)} {value.unit}</p>{e.receipt.void&&<p>Este recebimento foi anulado. O aceite original está preservado no histórico e excluído do aceite efetivo.</p>}</>}
 {e.kind==='rejected'&&<p>Entrega: {e.rejection.delivery_reference} · Recusado: {q(e.rejection.delivered_milli)} {value.unit}. Sem entrada de estoque.</p>}
 {e.kind==='voided'&&<p>Recebimento corrigido: {e.void.receipt_id} · Compensação: {q(e.void.quantity_milli)} {value.unit} · Local: {e.void.location_id}. Correção de lançamento; não comprova devolução ao fornecedor.</p>}
 </details>;
}
export default function LocalReceivingHistory(){
 const {capabilities}=useLocalAccess(),canHistory=!!capabilities?.permissions.includes('manage_stock');
 const orders=useReadTask<PurchaseSearch>(),history=useReadTask<ReceivingHistory>();
 const [supplier,setSupplier]=useState(''),[product,setProduct]=useState(''),[orderID,setOrderID]=useState(''),[offset,setOffset]=useState(0),[historyOffset,setHistoryOffset]=useState(0);
 function loadOrders(value=0){setOffset(value);void orders.run(t=>client.orders(t,supplier.trim(),product.trim(),value));}
 function loadHistory(value=0,id=orderID.trim()){setHistoryOffset(value);void history.run(t=>client.history(t,id,value));}
 return <main className="brand-app-content operation-page"><header><p className="brand-eyebrow">COMPRAS LOCAIS</p><h1>Pedidos e histórico de recebimento</h1><p>Confirmação de recebimento local e situação comercial são estados distintos. O pedido local não comprova envio ou aceite remoto.</p><Link className="brand-secondary" to="/local/orders">Abrir fornecedores e criar pedido de reposição</Link></header>
 <ReadSection title="Encontrar pedidos"><form className="operation-form" onSubmit={e=>{e.preventDefault();loadOrders();}}><label className="brand-field">ID do fornecedor (opcional)<input maxLength={128} value={supplier} onChange={e=>{setSupplier(e.target.value);orders.clear();}}/></label><label className="brand-field">ID do produto (opcional)<input maxLength={128} value={product} onChange={e=>{setProduct(e.target.value);orders.clear();}}/></label><button className="brand-primary" disabled={orders.busy}>Consultar pedidos</button></form><ReadState task={orders}/>{orders.data&&<><p>{orders.data.total_count} pedidos encontrados.</p>{orders.data.items.map(o=><details key={o.id}><summary>{o.supplier_name} · {o.status==='cancelled'?'Cancelado':'Local, não enviado'} · {statuses[o.receiving_status]}</summary><p className="operation-id">Pedido: {o.id}<br/>Criado em: {o.created_at}</p>{o.items.map(i=><p key={i.product_id}>{i.sku} · {i.name}: {q(i.quantity_milli)} {i.unit}</p>)}{canHistory&&<button className="brand-secondary" disabled={history.busy} onClick={()=>{setOrderID(o.id);loadHistory(0,o.id);}}>Consultar histórico deste pedido</button>}</details>)}<Pages offset={offset} more={orders.data.has_more} busy={orders.busy} change={loadOrders}/></>}</ReadSection>
 {canHistory?<ReadSection title="Recebimentos, recusas e anulações"><form className="operation-form" onSubmit={e=>{e.preventDefault();loadHistory();}}><label className="brand-field">ID do pedido<input required maxLength={128} value={orderID} onChange={e=>{setOrderID(e.target.value);history.clear();}}/></label><button className="brand-primary" disabled={history.busy}>Consultar histórico</button></form><ReadState task={history}/>{history.data&&<><p>{statuses[history.data.receiving_status]} · {history.data.commercial_status==='cancelled'?'Pedido cancelado':'Pedido local, não enviado'} · {history.data.total_count} eventos.</p><dl className="operation-metrics">{[['Planejado',history.data.totals.planned_milli],['Aceito efetivo',history.data.totals.effective_accepted_milli],['Pendente',history.data.totals.remaining_milli],['Entregue efetivo',history.data.totals.effective_delivered_milli],['Recusado parcial efetivo',history.data.totals.partial_rejected_milli],['Recusado integral acumulado',history.data.totals.fully_rejected_milli_exact],['Aceito original acumulado',history.data.totals.recorded_accepted_milli_exact],['Aceito anulado acumulado',history.data.totals.voided_accepted_milli_exact]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{q(value)} {history.data!.unit}</dd></div>)}</dl><p>Totais globais do pedido. Originais e anulações aparecem separadamente; não some eventos como novas mercadorias.</p>{history.data.items.map(e=><Entry key={`${e.kind}:${e.id}`} entry={e}/>)}{!history.data.items.length&&<p>Nenhum evento nesta página.</p>}<Pages offset={historyOffset} more={history.data.has_more} busy={history.busy} change={loadHistory}/></>}</ReadSection>:<p>O histórico de recebimento exige também permissão de estoque.</p>}
 </main>;
}
