import {useEffect, useRef, useState} from 'react';
import {useLocalAccess} from '../../../core/local/LocalAccess';
import {LocalAPIError, formatLocalCents} from '../../../core/local/localClient.mjs';
import {localErrorMessage, useLocalSession} from '../../../core/local/useLocalSession';
import {createCatalogSearch} from '../../../core/local/catalogSearch.mjs';
import type {CatalogSearchProduct} from '../../../core/local/catalogSearch.mjs';
import {parseMoney} from '../../../core/local/posModel.mjs';
import {comparisonLink, comparisonQuery, createComparisonClient, manualComparison, persistSitePending, readSitePending, releaseRefusedSite, resolveSitePending, sitePendingKey} from '../../../core/local/comparisonClient.mjs';
import type {ComparisonSite, ManualComparison, PendingSite, SiteInput} from '../../../core/local/comparisonClient.mjs';
import './comparison.css';

const client=createComparisonClient(), searchCatalog=createCatalogSearch();
const presets=[
 {name:'Centauro',origin:'https://www.centauro.com.br',search_template:'https://www.centauro.com.br/busca/{query}'},
 {name:'Netshoes',origin:'https://www.netshoes.com.br',search_template:'https://www.netshoes.com.br/busca?nsCat=Natural&q={query}'},
 {name:'Adidas',origin:'https://www.adidas.com.br',search_template:''},
];
type Observation=ManualComparison & {recorded_at:string};
function ManualQuote({site,onRecord}:{site:ComparisonSite;onRecord:(value:Observation)=>void}) {
 const [price,setPrice]=useState(''),[freight,setFreight]=useState(''),[available,setAvailable]=useState('unknown'),[identical,setIdentical]=useState(false),[error,setError]=useState('');
 return <details className="comparison-manual"><summary>Registrar conferência manual</summary><form className="comparison-quote-form" onSubmit={e=>{e.preventDefault();setError('');try{const value=manualComparison(parseMoney(price),freight.trim()===''?null:parseMoney(freight),available,identical);onRecord({...value,recorded_at:new Date().toISOString()});}catch(e){setError(localErrorMessage(e));}}}>
  <label>Preço visto (R$)<input required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} /></label>
  <label>Frete para o destino (R$)<input inputMode="decimal" placeholder="Vazio = desconhecido" value={freight} onChange={e=>setFreight(e.target.value)}/></label>
  <label>Disponibilidade da variante<select value={available} onChange={e=>setAvailable(e.target.value)}><option value="unknown">Não conferida</option><option value="available">Disponível no site</option><option value="unavailable">Indisponível no site</option></select></label>
  <label className="comparison-check"><input type="checkbox" checked={identical} onChange={e=>setIdentical(e.target.checked)}/>Conferi o mesmo modelo, variante, quantidade/unidade e condição de pagamento.</label>
  <button className="brand-secondary">Registrar para {site.name}</button>{error&&<p role="alert">{error}</p>}
 </form></details>;
}
export default function LocalComparison() {
 const token=useLocalSession(s=>s.token),session=useLocalSession(s=>s.session),invalidate=useLocalSession(s=>s.invalidate);
 const {capabilities}=useLocalAccess();
 const manage=!!capabilities?.permissions.includes('manage_stock'),canWrite=manage&&capabilities?.license.state==='active';
 const key=session?sitePendingKey(session):'';
 const [sites,setSites]=useState<ComparisonSite[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [pending,setPending]=useState<PendingSite|null>(null),[storageBlocked,setStorageBlocked]=useState(false);
 const [editing,setEditing]=useState<ComparisonSite|null>(null),[name,setName]=useState(''),[origin,setOrigin]=useState(''),[template,setTemplate]=useState(''),[status,setStatus]=useState<'active'|'inactive'>('active');
 const [searchRevision,setSearchRevision]=useState(0);
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[products,setProducts]=useState<CatalogSearchProduct[]>([]),[productLoading,setProductLoading]=useState(false),[productError,setProductError]=useState(''),[productTotal,setProductTotal]=useState(0);
 const [product,setProduct]=useState<CatalogSearchProduct|null>(null),[variant,setVariant]=useState(''),[condition,setCondition]=useState('À vista'),[target,setTarget]=useState<{product:CatalogSearchProduct;variant:string;condition:string;query:string}|null>(null),[observations,setObservations]=useState<Record<string,Observation>>({});
 const latch=useRef(false);
 useEffect(()=>{setPending(null);setStorageBlocked(false);try{if(key)setPending(readSitePending(localStorage,key));}catch{setStorageBlocked(true);setError('Não foi possível ler a operação pendente. Cadastros bloqueados até conferir o armazenamento.');}},[key]);
 useEffect(()=>{if(!token)return;const abort=new AbortController();setLoading(true);setSites([]);client.sites(token,abort.signal).then(v=>{if(!abort.signal.aborted){setSites(v.items);setObservations({});}}).catch(e=>{if(!abort.signal.aborted){setError(localErrorMessage(e));if(e instanceof LocalAPIError&&e.status===401)invalidate();}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[token,reload,invalidate]);
 useEffect(()=>{if(!token||!submitted)return;const abort=new AbortController();setProductLoading(true);setProducts([]);setProductError('');searchCatalog(token,{q:submitted},abort.signal).then(v=>{if(!abort.signal.aborted){setProducts(v.items);setProductTotal(v.total);}}).catch(e=>{if(!abort.signal.aborted){setProductError(localErrorMessage(e));if(e instanceof LocalAPIError&&e.status===401)invalidate();}}).finally(()=>{if(!abort.signal.aborted)setProductLoading(false);});return()=>abort.abort();},[token,submitted,invalidate,searchRevision]);
 function showFailure(e:unknown){setError(localErrorMessage(e));if(e instanceof LocalAPIError&&e.status===401)invalidate();}
 function fill(site:ComparisonSite|null){setEditing(site);setName(site?.name||'');setOrigin(site?.origin||'');setTemplate(site?.search_template||'');setStatus(site?.status||'active');}
 async function locked(action:()=>Promise<void>){if(latch.current||!token||!key)return;latch.current=true;setBusy(true);setError('');setNotice('');try{if(!navigator.locks)throw new Error('Use o navegador em localhost com proteção entre abas.');await navigator.locks.request(key,{ifAvailable:true},async lock=>{if(!lock)throw new Error('Outra aba está alterando os sites.');await action();});}catch(e){showFailure(e);}finally{try{setPending(readSitePending(localStorage,key));}catch{setStorageBlocked(true);}latch.current=false;setBusy(false);}}
 async function resolve(send:boolean){if(!token)return;const result=await resolveSitePending(client,token,localStorage,key,send);setPending(readSitePending(localStorage,key));if(result?.state==='confirmed'){setNotice('Configuração confirmada no banco local.');fill(null);setReload(v=>v+1);}else setNotice('Operação ainda não encontrada. Confira a conexão; a repetição explícita usa os mesmos identificadores.');}
 function save(e:React.FormEvent){e.preventDefault();if(!canWrite||pending||storageBlocked)return;void locked(async()=>{const input:SiteInput={operation_id:crypto.randomUUID(),id:editing?.id||crypto.randomUUID(),expected_revision:editing?.revision||0,name:name.trim(),origin:origin.trim(),search_template:template.trim(),status};persistSitePending(localStorage,key,input);setPending(readSitePending(localStorage,key));await resolve(true);});}
 const active=sites.filter(s=>s.status==='active');
 const ranked=active.map(s=>({site:s,observation:observations[s.id]})).filter(v=>v.observation?.eligible).sort((a,b)=>a.observation.total_cents!-b.observation.total_cents!);
 return <main className="brand-app-content comparison-page">
  <div className="brand-app-heading"><div><p className="brand-eyebrow">PESQUISA COMERCIAL</p><h1>Comparador de preços</h1><p className="brand-subtitle">Sites escolhidos pela empresa · comparação do mesmo produto e variante.</p></div><button className="brand-secondary" disabled={busy||loading} onClick={()=>{setError('');setReload(v=>v+1);}}>Atualizar sites</button></div>
  <p className="brand-message">Consulta automática de preço e estoque: integração ainda não configurada. Os links abrem a pesquisa no site; valores registrados abaixo são conferências manuais.</p>
  {error&&<p role="alert" className="brand-message error">{error}</p>}{notice&&<p role="status" className="brand-message">{notice}</p>}
  {pending&&<section className="brand-panel"><h2>Alteração pendente de confirmação</h2><p>{pending.input.name} · os identificadores originais estão preservados.</p><button className="brand-secondary" disabled={busy||!manage} onClick={()=>void locked(()=>resolve(false))}>Consultar resultado</button> <button className="brand-secondary" disabled={busy||!canWrite} onClick={()=>void locked(()=>resolve(true))}>Repetir mesma operação</button>{pending.state==='refused'&&<button className="brand-secondary" disabled={busy||!manage} onClick={()=>void locked(async()=>{const value=await releaseRefusedSite(client,token!,localStorage,key);setPending(null);setNotice(value.state==='released'?'Recusa e ausência confirmadas. Você pode corrigir o cadastro ou recarregar a revisão antes de editar.':'Operação confirmada.');setReload(v=>v+1);})}>Liberar edição após recusa confirmada</button>}<p>Uma falha de resposta não libera um novo cadastro ou edição.</p></section>}
  <section className="brand-panel"><h2>1. Escolher produto</h2><form className="comparison-search" onSubmit={e=>{e.preventDefault();setSubmitted(query.trim());setSearchRevision(v=>v+1);}}><label>Buscar no catálogo da empresa<input type="search" required maxLength={240} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, SKU ou código de barras"/></label><button className="brand-small-primary" disabled={productLoading}>Buscar</button></form>
   {productLoading&&<p role="status">Consultando catálogo…</p>}{productError&&<p role="alert">{productError}</p>}
   {!productLoading&&submitted&&!productError&&<><p className="brand-state">{productTotal} resultado(s). Exibindo até 50; refine a busca para encontrar o modelo exato.</p><div className="comparison-product-list">{products.map(p=><button key={p.id} className={`brand-secondary ${product?.id===p.id?'comparison-selected':''}`} onClick={()=>{setProduct(p);setVariant('');setTarget(null);setObservations({});}}>{p.name} · {p.sku} · {formatLocalCents(p.price_cents)} / {p.unit}{p.approximate?' · busca aproximada':''}</button>)}</div></>}
   {product&&<form className="comparison-target" onSubmit={e=>{e.preventDefault();if(!variant.trim()||!condition.trim()){setProductError('Informe a variante e a condição de pagamento.');return;}try{setTarget({product,variant:variant.trim(),condition:condition.trim(),query:comparisonQuery(product.name,variant.trim())});setObservations({});setProductError('');}catch(e){setProductError(localErrorMessage(e));}}}><p><strong>{product.name}</strong> · preço cadastrado: {formatLocalCents(product.price_cents)} / {product.unit}</p><label>Variante exata (tamanho, cor, capacidade ou embalagem)<input required maxLength={120} value={variant} onChange={e=>setVariant(e.target.value)} placeholder="Ex.: tamanho 40, preto; ou unidade sem variante"/></label><label>Condição de pagamento comparada<input required maxLength={80} value={condition} onChange={e=>setCondition(e.target.value)}/></label><button className="brand-small-primary" disabled={loading||!active.length}>Preparar consultas</button><p className="brand-state">Ao trocar produto ou condições, as conferências anteriores saem desta comparação.</p></form>}
  </section>
  <section className="brand-panel"><h2>2. Consultar os sites</h2>{loading?<p role="status">Consultando sites cadastrados…</p>:!active.length?<p>Nenhum site ativo. Uma pessoa com permissão de estoque pode cadastrar os sites abaixo.</p>:!target?<p>Escolha o produto e prepare as consultas.</p>:<><p><strong>{target.product.name}</strong> · {target.variant} · {target.condition}</p><p className="brand-state">Pesquisa enviada ao abrir o site: {target.query}. Confira a variante na página do produto.</p><div className="comparison-sites">{active.map(s=><article key={s.id} className="comparison-site"><h3>{s.name}</h3><p className="comparison-domain">{s.origin}</p><span className="comparison-badge">Conferência manual · sem API conectada</span><p><a className="brand-secondary" href={comparisonLink(s,target.query)} target="_blank" rel="noopener noreferrer">{s.search_template?'Pesquisar neste site':'Abrir site para pesquisar'} ↗</a></p>{!s.search_template&&<p className="brand-state">Este site ainda não tem endereço de busca configurado.</p>}<ManualQuote key={JSON.stringify([target,s.id,s.revision])} site={s} onRecord={v=>setObservations(previous=>({...previous,[s.id]:v}))}/>{observations[s.id]&&<p className="brand-state">Conferência registrada nesta tela em {new Date(observations[s.id].recorded_at).toLocaleString('pt-BR')}.</p>}</article>)}</div></>}
  </section>
  {target&&<section className="brand-panel"><h2>3. Comparar as conferências</h2><div className="brand-table-scroll"><table className="brand-table"><thead><tr><th scope="col">Site</th><th scope="col">Preço visto</th><th scope="col">Frete</th><th scope="col">Total</th><th scope="col">Estado</th></tr></thead><tbody>{active.map(s=>{const o=observations[s.id];return <tr key={s.id}><td>{s.name}</td><td className="comparison-money">{o?formatLocalCents(o.price_cents):'Não consultado'}</td><td className="comparison-money">{o&&o.freight_cents!==null?formatLocalCents(o.freight_cents):'Não conferido'}</td><td className="comparison-money">{o&&o.total_cents!==null?formatLocalCents(o.total_cents):'Não calculado'}</td><td>{!o?'Aguardando conferência manual':o.availability==='unavailable'?'Variante indisponível':o.availability==='unknown'?'Disponibilidade não conferida':!o.identical?'Equivalência não confirmada':o.freight_cents===null?'Frete pendente':'Conferência manual completa'}</td></tr>;})}</tbody></table></div>{ranked.length>0&&<p className="brand-message">Menor total entre as conferências manuais completas: {ranked[0].site.name} · {formatLocalCents(ranked[0].observation.total_cents!)}. Não é uma cotação automática; confira validade, vendedor e condições antes de usar.</p>}<p className="brand-state">As conferências ficam somente nesta tela e são perdidas ao sair ou recarregar. Não alteram preço, estoque, venda ou pedido.</p></section>}
  {manage&&<details className="brand-panel comparison-config" open={!!editing}><summary>Gerenciar sites ({sites.length}/32)</summary><p className="brand-state">Cadastro local da empresa. Apenas HTTPS, um registro por domínio. Inativar preserva o histórico.</p>
   <div className="comparison-presets">{presets.map(p=><button key={p.name} className="brand-secondary" disabled={busy||!!pending||storageBlocked||!canWrite} onClick={()=>{fill(null);setName(p.name);setOrigin(p.origin);setTemplate(p.search_template);}}>Preencher {p.name}</button>)}</div>
   <form className="comparison-config-form" onSubmit={save}><label>Nome do site<input required maxLength={120} value={name} disabled={busy||!!pending||storageBlocked||!canWrite} onChange={e=>setName(e.target.value)}/></label><label>Endereço principal<input required type="url" placeholder="https://www.exemplo.com.br" value={origin} disabled={busy||!!pending||storageBlocked||!canWrite} onChange={e=>setOrigin(e.target.value)}/></label><label className="comparison-wide">Endereço da busca (opcional)<input placeholder="https://www.exemplo.com.br/busca?q={query}" value={template} disabled={busy||!!pending||storageBlocked||!canWrite} onChange={e=>setTemplate(e.target.value)}/></label><p className="comparison-wide brand-state">Use {'{query}'} uma vez no caminho ou parâmetro da busca. Sem esse endereço, o botão abre a página principal para pesquisa manual.</p><label>Estado<select value={status} disabled={busy||!!pending||storageBlocked||!canWrite} onChange={e=>setStatus(e.target.value as 'active'|'inactive')}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label><button className="brand-small-primary" disabled={busy||!!pending||storageBlocked||!canWrite}>{editing?'Salvar nova revisão':'Cadastrar site'}</button>{editing&&<button type="button" className="brand-secondary" disabled={busy} onClick={()=>fill(null)}>Sair da edição</button>}</form>
   {!canWrite&&<p>Alterações exigem licença de estoque vigente.</p>}
   <ul className="comparison-config-list">{sites.map(s=><li key={s.id}><div><strong>{s.name}</strong><p>{s.origin} · {s.status==='active'?'Ativo':'Inativo'} · revisão {s.revision}</p></div><button className="brand-secondary" disabled={busy||!!pending||storageBlocked||!canWrite} onClick={()=>fill(s)}>Editar / inativar</button></li>)}</ul>
  </details>}
 </main>;
}
