import {useEffect,useRef,useState} from 'react';
import {useLocalSession} from '../../../core/local/useLocalSession';
import {useLocalAccess} from '../../../core/local/LocalAccess';
import {createReplenishmentClient,parseThreshold,restockKey,readRestockPending,persistRestockPending,resolveRestockPending} from '../../../core/local/replenishmentClient.mjs';
import type {RestockProduct,RestockSuggestion,RestockPending,RestockKind,RestockInput} from '../../../core/local/replenishmentClient.mjs';
const client=createReplenishmentClient();
const qty=(n:number)=>`${Math.floor(n/1000)},${String(n%1000).padStart(3,'0')}`;
const states:Record<string,string>={suggested:'Aguardando revisão',approved:'Aprovada',rejected:'Rejeitada',not_needed:'Sem necessidade'};
export default function ReplenishmentPanel({onChange}:{onChange:()=>Promise<void>}){
 const token=useLocalSession(s=>s.token),session=useLocalSession(s=>s.session);const {capabilities}=useLocalAccess();const key=session?restockKey(session):'';
 const manage=!!capabilities?.permissions.includes('manage_replenishment'),stock=!!capabilities?.permissions.includes('manage_stock'),active=capabilities?.license.state==='active';
 const [products,setProducts]=useState<RestockProduct[]>([]),[suggestions,setSuggestions]=useState<RestockSuggestion[]>([]),[product,setProduct]=useState(''),[minimum,setMinimum]=useState(''),[target,setTarget]=useState(''),[selected,setSelected]=useState(''),[reason,setReason]=useState('');
 const [offset,setOffset]=useState(0),[suggestionOffset,setSuggestionOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<RestockPending|null>(null),[storageError,setStorageError]=useState('');const latch=useRef(false);
 const chosen=products.find(p=>p.id===product),proposal=suggestions.find(s=>s.id===selected);
 async function load(){if(!token)return;const [p,s]=await Promise.all([client.products(token,offset),client.suggestions(token,suggestionOffset)]);setProducts(p);setSuggestions(s);}
 useEffect(()=>{let live=true;if(!token)return;setBusy(true);Promise.all([client.products(token,offset),client.suggestions(token,suggestionOffset)]).then(([p,s])=>{if(live){setProducts(p);setSuggestions(s);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[token,offset,suggestionOffset]);
 useEffect(()=>{try{setPending(readRestockPending(localStorage,key));setStorageError('');}catch{setStorageError('Operação pendente ilegível. Gravações bloqueadas neste navegador.');}},[key]);
 async function locked(fn:()=>Promise<void>){if(!token||!key||latch.current)return;latch.current=true;setBusy(true);setError('');setNotice('');try{if(!navigator.locks)throw new Error('Atualize o navegador: bloqueio entre abas necessário para gravar.');await navigator.locks.request(key,{ifAvailable:true},async lock=>{if(!lock)throw new Error('Outra aba está tratando a reposição. Aguarde.');await fn();});}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar a reposição.');}finally{try{setPending(readRestockPending(localStorage,key));}catch{setStorageError('Não foi possível conferir a operação pendente.');}latch.current=false;setBusy(false);}}
 async function resolve(send=false,discard=false){if(!token)return;const v=await resolveRestockPending(client,token,localStorage,key,send,discard);setNotice(v?.state==='confirmed'?'Operação confirmada no banco local.':v?.state==='discarded'?'Operação não gravada liberada para correção.':'Nenhum resultado encontrado. Uma repetição explícita usa os dados originais.');await load();await onChange();}
 async function start(kind:RestockKind,input:Omit<RestockInput,'operation_id'>){await locked(async()=>{persistRestockPending(localStorage,key,kind,{...input,operation_id:crypto.randomUUID()});await resolve(true);});}
 function choose(id:string){setProduct(id);const p=products.find(p=>p.id===id);setMinimum(p?.revision?qty(p.minimum_milli):'');setTarget(p?.revision?qty(p.target_milli):'');}
 const blocked=busy||!!pending||!!storageError||!active;
 return <section className="brand-panel" style={{display:'grid',gap:12}}><h2>Reposição pelo estoque real</h2><p>Configure a política, calcule e revise com motivo. A aprovação libera um pedido local; ainda não envia ao fornecedor nem recebe mercadoria.</p>
 {error&&<p className="brand-state" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{storageError&&<p role="alert">{storageError}</p>}
 {pending&&<div className="brand-state"><strong>Reposição pendente de confirmação</strong><p>Operação: {pending.input.operation_id} · {pending.kind==='policy'?'Política':pending.kind==='suggest'?'Cálculo':'Revisão'}</p><button className="brand-secondary" disabled={busy} onClick={()=>void locked(()=>resolve())}>Consultar resultado</button> <button className="brand-primary" disabled={busy||!active} onClick={()=>void locked(()=>resolve(true))}>Repetir mesma operação</button> {!pending.uncertain&&<button className="brand-secondary" disabled={busy} onClick={()=>void locked(()=>resolve(false,true))}>Liberar para corrigir</button>}<p>Um resultado incerto permanece preservado até confirmação.</p></div>}
 <label className="brand-field">Produto nesta loja<select value={product} disabled={busy||!!pending} onChange={e=>choose(e.target.value)}><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit}</option>)}</select></label>
 {chosen&&<p>Saldo disponível: <strong>{qty(chosen.balance_milli)} {chosen.unit}</strong> · {chosen.revision?`Política revisão ${chosen.revision}: mínimo ${qty(chosen.minimum_milli)}, alvo ${qty(chosen.target_milli)}`:'Sem política cadastrada'}</p>}
 {manage&&<form className="catalog-form" onSubmit={e=>{e.preventDefault();if(!chosen)return;try{const min=parseThreshold(minimum,chosen.unit),max=parseThreshold(target,chosen.unit);if(max<=min)throw new Error('O alvo deve ser maior que o mínimo.');void start('policy',{product_id:product,minimum_milli:min,target_milli:max});}catch(e){setError(e instanceof Error?e.message:'Quantidade inválida.');}}}><label className="brand-field">Mínimo ({chosen?.unit||'unidade do produto'})<input inputMode="decimal" required value={minimum} disabled={blocked||!chosen} onChange={e=>setMinimum(e.target.value)}/></label><label className="brand-field">Alvo<input inputMode="decimal" required value={target} disabled={blocked||!chosen} onChange={e=>setTarget(e.target.value)}/></label><button className="brand-primary" disabled={blocked||!chosen}>Salvar política</button></form>}
 {stock&&<button className="brand-primary" disabled={blocked||!chosen?.revision} onClick={()=>void start('suggest',{product_id:product})}>Calcular sugestão</button>}
 <p>O cálculo considera prateleira, depósito e recebimento. Abaixo do mínimo, sugere a quantidade necessária para alcançar o alvo.</p>
 <div><button className="brand-secondary" disabled={busy||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Produtos anteriores</button> <button className="brand-secondary" disabled={busy||products.length<50} onClick={()=>setOffset(v=>v+50)}>Mais produtos</button></div>
 <h3>Sugestões e decisões</h3><button className="brand-secondary" disabled={busy} onClick={()=>void locked(load)}>Atualizar saldo e sugestões</button>
 {!suggestions.length?<p>Nenhuma sugestão nesta página.</p>:<ul>{suggestions.map(s=><li key={s.id}><button className="brand-secondary" aria-pressed={selected===s.id} disabled={busy||!!pending} onClick={()=>{setSelected(s.id);setReason('');}}>{s.name} — {states[s.status]}</button><p>Saldo observado {qty(s.observed_milli)} · Repor {qty(s.recommended_milli)} {s.unit} · Política {s.policy_revision}</p>{s.stale&&<p>Desatualizada: saldo ou política mudou. Rejeite e calcule novamente.</p>}{s.reason&&<p>Motivo: {s.reason}</p>}{s.order_id&&<p>Pedido local criado: {s.order_id}</p>}</li>)}</ul>}
 {manage&&proposal?.status==='suggested'&&<div><label className="brand-field">Motivo da decisão<input required value={reason} disabled={blocked} onChange={e=>setReason(e.target.value)}/></label><button className="brand-primary" disabled={blocked||proposal.stale||!reason.trim()} onClick={()=>void start('review',{suggestion_id:selected,decision:'approved',reason:reason.trim()})}>Aprovar reposição</button> <button className="brand-secondary" disabled={blocked||!reason.trim()} onClick={()=>void start('review',{suggestion_id:selected,decision:'rejected',reason:reason.trim()})}>Rejeitar sugestão</button></div>}
 <div><button className="brand-secondary" disabled={busy||suggestionOffset===0} onClick={()=>setSuggestionOffset(v=>Math.max(0,v-50))}>Sugestões anteriores</button> <button className="brand-secondary" disabled={busy||suggestions.length<50} onClick={()=>setSuggestionOffset(v=>v+50)}>Mais sugestões</button></div>
 {!active&&<p>Consultas disponíveis. Gravações exigem contrato de pedidos vigente.</p>}
 </section>;
}
