import test from 'node:test';
import assert from 'node:assert/strict';
import {LocalAPIError} from '../src/core/local/localClient.mjs';
import {comparisonLink,comparisonQuery,createComparisonClient,manualComparison,persistSitePending,readSitePending,releaseRefusedSite,resolveSitePending,sitePendingKey,validComparisonOrigin,validComparisonTemplate} from '../src/core/local/comparisonClient.mjs';
import {allowedAreas,areaForRoute} from '../src/core/local/accessModel.mjs';
const input=()=>({operation_id:'op1',id:'site1',expected_revision:0,name:'Shop',origin:'https://shop.com.br',search_template:'https://shop.com.br/busca?q={query}',status:'active'});
const result=()=>({operation_id:'op1',site:{id:'site1',name:'Shop',origin:'https://shop.com.br',search_template:'https://shop.com.br/busca?q={query}',status:'active',revision:1,changed_at:'2026-10-06T12:00:00Z',mode:'external_link'},repeated:false});
const missing=()=>new LocalAPIError(404,'Not found');
function storage(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
const response=v=>new Response(JSON.stringify(v),{status:200});
test('comparison links stay HTTPS on registered origin and encode product variants',()=>{const s=result().site;const link=comparisonLink(s,'Tênis 40 & preto?');assert.equal(new URL(link).searchParams.get('q'),'Tênis 40 & preto?');for(const origin of ['http://shop.com.br','https://127.0.0.1','https://localhost','https://shop.local','https://user:pass@shop.com.br','https://shop.com.br:443','https://shop.com.br/path','https://example.123'])assert.equal(validComparisonOrigin(origin),false,origin);for(const template of ['javascript:alert(1)','https://evil.com/?q={query}','https://shop.com.br/?q={query}&a={query}','https://shop.com.br/#q={query}','https://user:pass@shop.com.br/?q={query}'])assert.equal(validComparisonTemplate(s.origin,template),false);assert.throws(()=>comparisonLink({...s,status:'inactive'},'Tênis'));assert.equal(comparisonLink({...s,search_template:''},'Tênis'),s.origin);});
test('comparison client validates revision results and never invents automatic integration',async()=>{const v={items:[result().site],limit:32,automatic_state:'not_configured'};assert.equal((await createComparisonClient(async()=>response(v)).sites('t')).items.length,1);await assert.rejects(createComparisonClient(async()=>response({...v,automatic_state:'connected'})).sites('t'));const fake=result();fake.site.revision=2;await assert.rejects(createComparisonClient(async()=>response(fake)).save('t',input()));let calls=0;await assert.rejects(createComparisonClient(async()=>{calls++;return response(result());}).save('t',{...input(),origin:'javascript:x'}));assert.equal(calls,0);});
test('lost site reply survives reload and lookup occurs without automatic repost',async()=>{const st=storage();persistSitePending(st,'k',input());let calls=0;const client={operation:async()=>{throw missing();},save:async()=>{calls++;throw new LocalAPIError(0,'Lost reply');}};await assert.rejects(resolveSitePending(client,'t',st,'k',true));assert.equal(readSitePending(st,'k').state,'uncertain');assert.deepEqual(await resolveSitePending(client,'t',st,'k',false),{state:'not_found'});assert.equal(calls,1);await assert.rejects(releaseRefusedSite(client,'t',st,'k'));client.operation=async()=>result();assert.equal((await resolveSitePending(client,'t',st,'k')).state,'confirmed');assert.equal(st.getItem('k'),null);});
test('query failure never posts, explicit retry keeps exact IDs and original payload',async()=>{const st=storage();persistSitePending(st,'k',input());let calls=0,seen;const client={operation:async()=>{throw new LocalAPIError(500,'Unavailable');},save:async v=>{calls++;seen=v;}};await assert.rejects(resolveSitePending(client,'t',st,'k',true));assert.equal(calls,0);let found=false;client.operation=async()=>{if(!found)throw missing();return result();};client.save=async(t,v)=>{seen=JSON.stringify(v);calls++;found=true;};assert.equal((await resolveSitePending(client,'t',st,'k',true)).state,'confirmed');assert.equal(seen,JSON.stringify(input()));assert.equal(calls,1);});
test('later refusal preserves earlier uncertainty; definite first refusal needs absent operation to release',async()=>{const st=storage();persistSitePending(st,'k',input());const client={operation:async()=>{throw missing();},save:async()=>{throw new LocalAPIError(409,'Conflict');}};await assert.rejects(resolveSitePending(client,'t',st,'k',true));assert.equal(readSitePending(st,'k').state,'refused');client.operation=async()=>{throw new LocalAPIError(500,'Unavailable');};await assert.rejects(releaseRefusedSite(client,'t',st,'k'));assert.ok(st.getItem('k'));client.operation=async()=>{throw missing();};assert.equal((await releaseRefusedSite(client,'t',st,'k')).state,'released');persistSitePending(st,'k',input());client.save=async()=>{throw new LocalAPIError(0,'Uncertain');};await assert.rejects(resolveSitePending(client,'t',st,'k',true));client.save=async()=>{throw new LocalAPIError(409,'Conflict');};await assert.rejects(resolveSitePending(client,'t',st,'k',true));assert.equal(readSitePending(st,'k').state,'uncertain');});
test('mismatched confirmed operation and persistence errors keep writes blocked',async()=>{const st=storage();persistSitePending(st,'k',input());const bad=result();bad.site.origin='https://other.com.br';await assert.rejects(resolveSitePending({operation:async()=>bad},'t',st,'k'));assert.ok(st.getItem('k'));assert.throws(()=>persistSitePending(st,'k',input()));assert.throws(()=>persistSitePending({getItem:()=>null,setItem:()=>{throw new Error('Storage blocked');}},'k',input()));st.setItem('k','{}');assert.throws(()=>readSitePending(st,'k'));});
test('manual ranking requires equivalent available variant and known freight with safe exact totals',()=>{assert.equal(manualComparison(10000,null,'available',true).eligible,false);assert.equal(manualComparison(10000,0,'unknown',true).eligible,false);assert.equal(manualComparison(10000,0,'available',false).eligible,false);const o=manualComparison(10000,1500,'available',true);assert.equal(o.total_cents,11500);assert.equal(o.source,'manual');assert.equal(o.eligible,true);assert.throws(()=>manualComparison(Number.MAX_SAFE_INTEGER,1,'available',true));assert.throws(()=>manualComparison(1.1,0,'available',true));});
test('comparator navigation requires inventory and current permission; pending state separates operators and devices',()=>{const c={role:'cashier',permissions:['view_catalog'],license:{state:'active',modules:['core','inventory']}};assert.ok(allowedAreas(c).includes('prices'));assert.ok(!allowedAreas({...c,license:{state:'active',modules:['core','staff']}}).includes('prices'));assert.equal(areaForRoute('/local/prices'),'prices');const s={tenant_id:'t',store_id:'s',device_id:'d',identity_id:'u'};for(const [k,v]of [['tenant_id','t2'],['store_id','s2'],['device_id','d2'],['identity_id','u2']])assert.notEqual(sitePendingKey(s),sitePendingKey({...s,[k]:v}));});

test('long accented product names produce a bounded valid external query without splitting characters',()=>{const q=comparisonQuery('Tênis '.repeat(80),'40 preto');assert.ok(new TextEncoder().encode(q).length<=240);assert.ok(!q.includes('�'));assert.throws(()=>comparisonQuery('\u0000',' '));});
