import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './productionExecution.fixture.mjs';import {canConfigureStages,prepareStagePlan,stageDecision,prepareStageState} from '../src/core/local/productionStages.mjs';
import {createProductionMutations,validProductionInput,persistProductionPending,resolveProductionPending,readProductionPending} from '../src/core/local/productionMutations.mjs';import {LocalAPIError} from '../src/core/local/localClient.mjs';
export const plan={operation_id:'plan',order_id:'o',stages:[{stage_id:'mix',name:'Misturar',responsible_id:'person'},{stage_id:'bake',name:'Assar',responsible_id:'person'}],reason:'Sequência'};
test('stage plan preserves operator sequence and refuses existing plan/materials',()=>{const v=fixture();let n=0;const input=prepareStagePlan(v,plan.stages,' Sequência ','plan',()=>plan.stages[n++].stage_id);assert.deepEqual(input,plan);assert.ok(canConfigureStages(fixture('planned')));for(const status of ['active','consumed'])assert.ok(!canConfigureStages(fixture('approved',status)));v.stages={order_id:'o',items:[]};assert.throws(()=>prepareStagePlan(v,plan.stages,'x','op',()=> 'id'));});
test('stage plan validates count distinct IDs responsible and UTF8 name',()=>{assert.ok(validProductionInput('stage_plan',plan));for(const stages of [[],Array(21).fill(plan.stages[0]),[plan.stages[0],plan.stages[0]],[{...plan.stages[0],name:'á'.repeat(61)}],[{...plan.stages[0],responsible_id:''}],[{...plan.stages[0],position:2}]])assert.ok(!validProductionInput('stage_plan',{...plan,stages}));});
test('stage receipt matches complete immutable plan even after progress',async()=>{let changed=false;const out={order_id:'o',status:'configured',revision:1,repeated:false};const c=createProductionMutations(async()=>new Response(JSON.stringify({kind:'stage_plan',input:{...plan,stages:changed?[...plan.stages].reverse():plan.stages},result:out})));assert.deepEqual(await c.operation('t','stage_plan',plan),out);changed=true;await assert.rejects(c.operation('t','stage_plan',plan));});
test('stage plan lost response reload confirms once without new IDs',async()=>{const map=new Map(),s={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};persistProductionPending(s,'k',{kind:'stage_plan',input:plan});let exists=false,writes=0;const c={operation:async()=>{if(!exists)throw new LocalAPIError(404,'missing');return {order_id:'o',status:'configured',revision:1,repeated:false};},write:async(_t,kind,input)=>{assert.equal(kind,'stage_plan');assert.deepEqual(input,plan);exists=true;writes++;throw new LocalAPIError(0,'lost');}};await assert.rejects(resolveProductionPending(c,'t',s,'k',true));assert.equal(readProductionPending(s,'k').uncertain,true);assert.equal((await resolveProductionPending(c,'t',s,'k')).state,'confirmed');assert.equal(writes,1);});
function trace(){const v=fixture('approved','consumed');v.stages={order_id:'o',items:plan.stages.map((s,n)=>({...s,position:n+1,status:'pending',revision:1}))};return v;}
test('only next stage responsible can progress after actual consumption',()=>{const v=trace();assert.deepEqual(stageDecision(v,'person'),{stage_id:'mix',expected_revision:1,status:'running'});assert.equal(stageDecision(v,'other'),null);v.materials.current.status='active';assert.equal(stageDecision(v,'person'),null);});
test('stage state uses consulted own revision and completed predecessor',()=>{const v=trace();v.stages.items[0].status='running';v.stages.items[0].revision=2;assert.deepEqual(prepareStageState(v,'person',' Executar ','op'),{operation_id:'op',order_id:'o',stage_id:'mix',expected_revision:2,status:'completed',reason:'Executar'});v.stages.items[0].status='completed';v.stages.items[0].revision=3;assert.equal(stageDecision(v,'person').stage_id,'bake');v.stages.items[1].status='completed';v.stages.items[1].revision=3;assert.equal(stageDecision(v,'person'),null);});
test('impossible skipped sequence and unknown stage state are refused',()=>{const v=trace();v.stages.items[1].status='completed';v.stages.items[1].revision=3;assert.equal(stageDecision(v,'person'),null);assert.ok(!validProductionInput('stage_state',{operation_id:'op',order_id:'o',stage_id:'mix',expected_revision:1,status:'completed',reason:'x'}));});
