import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './productionExecution.fixture.mjs';import {prepareStageState} from '../src/core/local/productionStages.mjs';import {createProductionMutations,persistProductionPending,readProductionPending,resolveProductionPending} from '../src/core/local/productionMutations.mjs';import {LocalAPIError} from '../src/core/local/localClient.mjs';
function trace(){const v=fixture('approved','consumed');v.stages={order_id:'o',items:[{stage_id:'mix',name:'Misturar',responsible_id:'person',position:1,status:'pending',revision:1}]};return v;}
const input={operation_id:'op',order_id:'o',stage_id:'mix',expected_revision:1,status:'running',reason:'Iniciar'};
const out={order_id:'o',stage_id:'mix',revision:2,status:'running',repeated:false};
test('POST targets stage state with exact responsible decision and frozen revision',async()=>{assert.deepEqual(prepareStageState(trace(),'person',' Iniciar ','op'),input);const c=createProductionMutations(async(url,opt)=>{assert.equal(url,'/local/v1/production/stages/state');assert.equal(opt.method,'POST');assert.deepEqual(JSON.parse(opt.body),input);return new Response(JSON.stringify(out));});assert.deepEqual(await c.write('token','stage_state',input),out);});
test('receipt confirms original running result even after current stage completed',async()=>{let wrong=false;const c=createProductionMutations(async()=>new Response(JSON.stringify({kind:'stage_state',input,result:wrong?{...out,status:'completed',revision:3}:out})));assert.deepEqual(await c.operation('t','stage_state',input),out);wrong=true;await assert.rejects(c.operation('t','stage_state',input));});
test('foreign actor or incomplete prior stage cannot prepare a progress action',()=>{assert.throws(()=>prepareStageState(trace(),'foreign','x','op'));const v=trace();v.stages.items.unshift({stage_id:'prior',name:'Antes',responsible_id:'other',position:1,status:'pending',revision:1});v.stages.items[1].position=2;assert.throws(()=>prepareStageState(v,'person','x','op'));});
test('stale refusal never updates expected revision or silently resends',async()=>{const map=new Map(),s={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};persistProductionPending(s,'k',{kind:'stage_state',input});let writes=0;const c={operation:async()=>{throw new LocalAPIError(404,'Absent');},write:async(_t,kind,got)=>{writes++;assert.equal(kind,'stage_state');assert.deepEqual(got,input);throw new LocalAPIError(409,'Stale');}};await assert.rejects(resolveProductionPending(c,'t',s,'k',true));assert.deepEqual(readProductionPending(s,'k').input,input);assert.equal(readProductionPending(s,'k').uncertain,false);assert.equal((await resolveProductionPending(c,'t',s,'k')).state,'missing');assert.equal(writes,1);});
