import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './productionExecution.test.mjs';import {prepareCompletion,validExecutionTrace} from '../src/core/local/productionExecution.mjs';
import {LocalAPIError} from '../src/core/local/localClient.mjs';import {persistProductionPending,resolveProductionPending,readProductionPending} from '../src/core/local/productionMutations.mjs';
test('completion preserves measured amount revision and original order',()=>{const v=fixture('approved','consumed');assert.deepEqual(prepareCompletion(v,'27',' Medido ','op','result'),{operation_id:'op',result_id:'result',order_id:'o',expected_revision:2,produced_milli:27000,reason:'Medido'});assert.equal(prepareCompletion(v,'0','Zero','op','result').produced_milli,0);});
test('completion refuses excess fractional units overflow and exponent',()=>{const v=fixture('approved','consumed');for(const q of ['30.001','31','0.001','-1','1e1','27.0000','9007199254740.992',''])assert.throws(()=>prepareCompletion(v,q,'Medido','op','result'));assert.throws(()=>prepareCompletion(v,'27','á'.repeat(128),'op','result'));});
test('mass output remains explicit and accepts exact three decimal measurement',()=>{const v=fixture('approved','consumed');v.order.recipe.output_unit='kg';assert.equal(prepareCompletion(v,'27,001','Pesado','op','result').produced_milli,27001);v.order.recipe.output_unit='box';assert.throws(()=>prepareCompletion(v,'27','Pesado','op','result'));});
test('wrong revision or absent consumption never creates completion input',()=>{for(const v of [fixture(),fixture('approved','active'),fixture('planned','consumed'),{...fixture('approved','consumed'),order:{...fixture().order,revision:2147483647}}])assert.throws(()=>prepareCompletion(v,'27','Medido','op','result'));});
test('completed trace rejects result from another local or unbalanced total',()=>{const v=fixture('completed','consumed');v.order.revision=3;v.result={result_id:'result',order_id:'o',reservation_id:'res',product_id:'bread',location_id:'room',unit:'unit',planned_milli:30000,produced_milli:27000,shortfall_milli:3000,revision:3,status:'completed',repeated:false,operation_id:'op',actor_id:'person',device_id:'device',created_at:'now',reason:'Medido'};assert.ok(validExecutionTrace(v,'o'));v.result.location_id='other';assert.ok(!validExecutionTrace(v,'o'));v.result.location_id='room';v.result.shortfall_milli--;assert.ok(!validExecutionTrace(v,'o'));});
test('lost result retries same frozen input and never invokes reserve or consume',async()=>{const map=new Map(),s={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const input=prepareCompletion(fixture('approved','consumed'),'0','Zero','op','result');persistProductionPending(s,'k',{kind:'result',input});let sent=0,exists=false;const client={operation:async(kind,got)=>{assert.equal(kind,'result');assert.deepEqual(got,input);if(!exists)throw new LocalAPIError(404,'Absent');return {result_id:'result'};},write:async(_t,kind,got)=>{assert.equal(kind,'result');assert.deepEqual(got,input);sent++;if(sent===1)throw new LocalAPIError(0,'Lost');exists=true;return {};}};
 // Real client signature includes token before kind and input.
 client.operation=async(_t,kind,got)=>{assert.equal(kind,'result');assert.deepEqual(got,input);if(!exists)throw new LocalAPIError(404,'Absent');return {result_id:'result'};};
 await assert.rejects(resolveProductionPending(client,'t',s,'k',true));assert.equal(readProductionPending(s,'k').uncertain,true);await assert.rejects(resolveProductionPending(client,'t',s,'k',false,true));assert.equal((await resolveProductionPending(client,'t',s,'k',true)).state,'confirmed');assert.equal(sent,2);assert.equal(readProductionPending(s,'k'),null);
});
