import test from 'node:test';import assert from 'node:assert/strict';
import {createProductionStageHistory,validStageHistoryEvent} from '../src/core/local/productionStageHistory.mjs';
const input={operation_id:'op',order_id:'o',stage_id:'mix',expected_revision:1,status:'running',reason:'Iniciar'};
const event={sequence:3,operation_id:'op',device_id:'d',actor_id:'person',kind:'running',reason:'Iniciar',request:input,result:{order_id:'o',stage_id:'mix',status:'running',revision:2,repeated:false},created_at:'2026-10-09T20:30:00Z'};
test('historical stage event retains original revision instead of latest stage',()=>{assert.ok(validStageHistoryEvent(event,'o'));assert.ok(!validStageHistoryEvent({...event,result:{...event.result,revision:3,status:'completed'}},'o'));assert.ok(!validStageHistoryEvent(event,'other'));});
test('history refuses future kinds bad operator or changed original request',()=>{for(const change of [{kind:'future'},{actor_id:''},{reason:'Changed'},{sequence:9007199254740992},{request:{...input,expected_revision:2}},{request:{...input,tenant_id:'foreign'}}])assert.ok(!validStageHistoryEvent({...event,...change},'o'));});
test('stage history is GET paginated without POST or cookies',async()=>{const c=createProductionStageHistory(async(url,opt)=>{assert.equal(url,'/local/v1/production/orders/o/stages/history?offset=50');assert.equal(opt.method,'GET');assert.equal(opt.credentials,'omit');return new Response(JSON.stringify({items:[event]}));});assert.deepEqual(await c.history('token','o',50),[event]);});
test('unordered duplicate oversized and foreign pages are rejected',async()=>{for(const items of [[event,event],[{...event,sequence:5},event],Array(51).fill(event),[{...event,request:{...input,order_id:'other'}}]]){const c=createProductionStageHistory(async()=>new Response(JSON.stringify({items})));await assert.rejects(c.history('t','o'));}});
test('empty pages stay empty and refused history never turns into success',async()=>{const empty=createProductionStageHistory(async()=>new Response(JSON.stringify({items:[]})));assert.deepEqual(await empty.history('t','o'),[]);const bad=createProductionStageHistory(async()=>new Response(null,{status:403}));await assert.rejects(bad.history('t','o'),e=>e.status===403);let calls=0;const c=createProductionStageHistory(async()=>{calls++;throw Error('network');});await assert.rejects(c.history('t','o',-1));await assert.rejects(c.history('t','o',1.5));assert.equal(calls,0);});
