import OrderPlanner from './OrderPlanner';
import RecipeEditor from './RecipeEditor';
import {ProductionPending} from './ProductionPending';
import {useState} from 'react';
import {createProductionRead} from '../../../core/local/productionRead.mjs';
import type {RecipeVersion,OrderPage,Capacity} from '../../../core/local/productionRead.mjs';
import {exactQuantity as q} from '../../../core/local/operationsRead.mjs';
import {useReadTask,ReadState,ReadSection,Pages} from './readPanel';
const client=createProductionRead();
const states:Record<string,string>={planned:'Planejada',approved:'Aprovada',cancelled:'Cancelada',completed:'Concluída'};
export default function LocalProduction(){
  const recipes=useReadTask<RecipeVersion[]>(),orders=useReadTask<OrderPage>(),capacity=useReadTask<Capacity>();
  const [recipeID,setRecipeID]=useState(''),[recipeOffset,setRecipeOffset]=useState(0),[orderOffset,setOrderOffset]=useState(0),[status,setStatus]=useState(''),[version,setVersion]=useState(''),[location,setLocation]=useState('');
  function loadRecipes(offset=0){setRecipeOffset(offset);void recipes.run(t=>client.versions(t,offset,recipeID.trim()));}
  function loadOrders(offset=0){setOrderOffset(offset);void orders.run(t=>client.orders(t,status,offset));}
  return <main className="brand-app-content operation-page"><ProductionPending><header><p className="brand-eyebrow">PRODUÇÃO LOCAL</p><h1>Receitas e ordens</h1><p>Quantidades em milésimos da unidade indicada. Consultar capacidade não reserva ingredientes.</p></header>
    <RecipeEditor/>
    <OrderPlanner/>
    <ReadSection title="Versões das receitas"><form className="operation-form" onSubmit={e=>{e.preventDefault();loadRecipes();}}><label className="brand-field">ID da receita (opcional)<input maxLength={128} value={recipeID} onChange={e=>{setRecipeID(e.target.value);recipes.clear();}}/></label><button className="brand-primary" disabled={recipes.busy}>Consultar versões</button></form><ReadState task={recipes}/>
      {recipes.data&&<><p>{recipes.data.length?'Versões preservadas desta página.':'Nenhuma versão nesta página.'}</p>{recipes.data.map(v=><details key={v.version_id}><summary>{v.name} · versão {v.revision} · {q(v.yield_milli)} {v.output_unit}</summary><p className="operation-id">Receita: {v.recipe_id}<br/>Versão: {v.version_id}<br/>Produto resultante: {v.output_product_id}</p><ul>{v.ingredients.map(i=><li key={i.product_id}>{i.product_id}: {q(i.quantity_milli)} {i.unit}</li>)}</ul><button className="brand-secondary" onClick={()=>{setVersion(v.version_id);capacity.clear();}}>Usar na consulta de capacidade</button></details>)}<Pages offset={recipeOffset} more={recipes.data.length===50} busy={recipes.busy} change={loadRecipes}/></>}
    </ReadSection>
    <ReadSection title="Capacidade por versão e local"><form className="operation-form" onSubmit={e=>{e.preventDefault();void capacity.run(t=>client.capacity(t,version.trim(),location.trim()));}}><label className="brand-field">ID da versão<input required maxLength={128} value={version} onChange={e=>{setVersion(e.target.value);capacity.clear();}}/></label><label className="brand-field">ID do local de estoque<input required maxLength={128} value={location} onChange={e=>{setLocation(e.target.value);capacity.clear();}}/></label><button className="brand-primary" disabled={capacity.busy}>Calcular capacidade</button></form><ReadState task={capacity}/>
      <p>Cada versão é uma alternativa independente. Não some capacidades de receitas que usam o mesmo estoque.</p>{capacity.data?.alternatives.map(c=><div key={c.version_id}><p>Disponibilidade consultada em {capacity.data!.measured_at}.</p><dl className="operation-metrics"><div><dt>Batidas completas possíveis</dt><dd>{c.possible_batches}</dd></div><div><dt>Produto resultante possível</dt><dd>{q(c.possible_output_milli)} {c.output_unit}</dd></div></dl><div className="operation-table-wrap"><table className="operation-table"><caption>Ingredientes e limites desta versão</caption><thead><tr><th>Produto</th><th>Por batida</th><th>Saldo disponível</th><th>Conversão estoque → receita</th><th>Batidas</th></tr></thead><tbody>{c.materials.map(m=><tr key={m.product_id}><td className="operation-id">{m.product_id}{m.limiting&&<strong> · Limitante</strong>}</td><td>{q(m.required_milli)} {m.recipe_unit}</td><td>{q(m.stock_milli)} {m.stock_unit}</td><td>{m.conversion_numerator}/{m.conversion_denominator}</td><td>{m.possible_batches}</td></tr>)}</tbody></table></div></div>)}
    </ReadSection>
    <ReadSection title="Ordens de produção"><form className="operation-form" onSubmit={e=>{e.preventDefault();loadOrders();}}><label className="brand-field">Estado<select value={status} onChange={e=>{setStatus(e.target.value);orders.clear();}}><option value="">Todos</option>{Object.entries(states).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></label><button className="brand-primary" disabled={orders.busy}>Consultar ordens</button></form><ReadState task={orders}/>{orders.data&&<><p>{orders.data.total_count} ordens encontradas. Planejar, aprovar e concluir são operações distintas.</p>{orders.data.items.map(o=><details key={o.id}><summary>{o.recipe.name} · {states[o.status]} · {q(o.planned_output_milli)} {o.recipe.output_unit}</summary><p className="operation-id">Ordem: {o.id}<br/>Versão imutável: {o.version_id} · revisão {o.recipe.revision}<br/>Local: {o.location_id}<br/>Responsável: {o.responsible_id}<br/>Batidas planejadas: {o.planned_batches}<br/>Criada em: {o.created_at}</p><ul>{o.recipe.ingredients.map(i=><li key={i.product_id}>{i.product_id}: {q(i.quantity_milli)} {i.unit} por batida</li>)}</ul></details>)}<Pages offset={orderOffset} more={orders.data.has_more} busy={orders.busy} change={loadOrders}/></>}</ReadSection>
  </ProductionPending></main>;
}
