import {useState} from 'react';
import {createProductionQuality} from '../../../core/local/productionQuality.mjs';
import type {QualityAudit} from '../../../core/local/productionQuality.mjs';
import {prepareQuality} from '../../../core/local/productionLotActions.mjs';
import {exactQuantity as q} from '../../../core/local/operationsRead.mjs';
import {localErrorMessage} from '../../../core/local/useLocalSession';
import {useReadTask,ReadState,ReadSection} from './readPanel';
import {useProductionMutations} from './ProductionPending';
const client=createProductionQuality();
export default function ProductionQualityReview(){
 const loaded=useReadTask<QualityAudit>(),mutations=useProductionMutations();const [lotID,setLotID]=useState(''),[status,setStatus]=useState<''|'passed'|'failed'>(''),[criterion,setCriterion]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false);
 function reset(){setStatus('');setCriterion('');setReason('');setConfirm(false);}
 let ready=false,error='';if(loaded.data&&status&&criterion&&reason){try{prepareQuality(loaded.data,status,criterion,reason,'preview');ready=true;}catch(e){error=localErrorMessage(e);}}
 async function save(){if(!loaded.data||!status||!ready||!confirm)return;const audit=loaded.data;const ok=await mutations.submit(()=>({kind:'quality',input:prepareQuality(audit,status,criterion,reason,crypto.randomUUID())}));if(ok){loaded.clear();reset();}}
 return <ReadSection title="Registrar avaliação humana de qualidade"><p>Informe seu parecer, critério e motivo após conferir o lote. O sistema registra sua decisão; não calcula aprovação nem transforma o parecer em liberação sanitária ou bloqueio de venda.</p><form className="operation-form" onSubmit={e=>{e.preventDefault();reset();void loaded.run(t=>client.audit(t,lotID.trim()));}}><label className="brand-field">ID do lote<input required maxLength={128} value={lotID} onChange={e=>{setLotID(e.target.value);loaded.clear();reset();}}/></label><button className="brand-secondary" disabled={loaded.busy||mutations.busy}>Consultar lote e revisão da qualidade</button></form><ReadState task={loaded}/>
 {loaded.data&&<><p className="operation-id">Lote: {loaded.data.lot.id}<br/>Resultado: {loaded.data.lot.result_id}<br/>Produto: {loaded.data.lot.product_id}</p><p>Código {loaded.data.lot.code} · {q(loaded.data.lot.quantity_milli)} {loaded.data.lot.unit}. Fabricação {loaded.data.lot.manufactured_on}; validade {loaded.data.lot.expires_on||'não informada'}.<br/>Revisão consultada da qualidade: {loaded.data.quality.revision}. Parecer atual: {loaded.data.quality.status==='not_assessed'?'Não avaliado':loaded.data.quality.status==='passed'?'Aprovado pelo avaliador':'Reprovado pelo avaliador'}.</p>{loaded.data.lot.status==='recorded'?<><label className="brand-field">Novo parecer<select value={status} disabled={mutations.blocked} onChange={e=>{setStatus(e.target.value as ''|'passed'|'failed');setConfirm(false);}}><option value="">Selecione seu parecer</option><option value="passed">Aprovado pelo avaliador</option><option value="failed">Reprovado pelo avaliador</option></select></label><label className="brand-field">Critério da avaliação<textarea maxLength={255} disabled={mutations.blocked} value={criterion} onChange={e=>{setCriterion(e.target.value);setConfirm(false);}}/></label><label className="brand-field">Motivo do parecer<textarea maxLength={255} disabled={mutations.blocked} value={reason} onChange={e=>{setReason(e.target.value);setConfirm(false);}}/></label>{error&&<p role="alert">{error}</p>}{ready&&<p>Registrar novo parecer {status==='passed'?'aprovado':'reprovado'}, preservando avaliações anteriores, com revisão {loaded.data.quality.revision+1}.</p>}<label><input type="checkbox" disabled={mutations.blocked} checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> Confirmo meu parecer e seus fundamentos para este lote.</label><button className="brand-primary" disabled={mutations.blocked||!ready||!confirm} onClick={()=>void save()}>Registrar parecer auditado</button></>:<p>Lote anulado: novas avaliações são recusadas. Consulte o histórico preservado.</p>}<p>Nova avaliação cria outra revisão; não sobrescreve o parecer anterior. Conflitos exigem nova consulta e decisão explícita.</p></>}
 </ReadSection>;
}
