import {useState} from 'react';
import {createProductionLots} from '../../../core/local/productionLots.mjs';
import {prepareLot} from '../../../core/local/productionLotActions.mjs';
import type {LotSummary} from '../../../core/local/productionLots.mjs';
import {exactQuantity as q} from '../../../core/local/operationsRead.mjs';
import {localErrorMessage} from '../../../core/local/useLocalSession';
import {useReadTask,ReadState,ReadSection} from './readPanel';
import {useProductionMutations} from './ProductionPending';
const client=createProductionLots();
export default function ProductionLotDeclaration(){
 const loaded=useReadTask<LotSummary>(),mutations=useProductionMutations();const [resultID,setResultID]=useState(''),[quantity,setQuantity]=useState(''),[code,setCode]=useState(''),[made,setMade]=useState(''),[expiry,setExpiry]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false);
 function reset(){setQuantity('');setCode('');setMade('');setExpiry('');setReason('');setConfirm(false);}
 let measured:number|undefined,error='';if(loaded.data&&quantity&&code&&made&&reason){try{measured=prepareLot(loaded.data,quantity,code,made,expiry,reason,'preview','preview-lot').quantity_milli;}catch(e){error=localErrorMessage(e);}}
 async function save(){if(!loaded.data||!confirm||measured===undefined)return;const summary=loaded.data;const ok=await mutations.submit(()=>({kind:'lot',input:prepareLot(summary,quantity,code,made,expiry,reason,crypto.randomUUID(),crypto.randomUUID())}));if(ok){loaded.clear();reset();}}
 return <ReadSection title="Declarar lote do produto acabado"><p>Atribua uma quantidade já produzida a um lote com código e datas declaradas. Não cria outra entrada de estoque e não presume aprovação de qualidade.</p><form className="operation-form" onSubmit={e=>{e.preventDefault();reset();void loaded.run(t=>client.summary(t,resultID.trim()));}}><label className="brand-field">ID do resultado<input required maxLength={128} value={resultID} onChange={e=>{setResultID(e.target.value);loaded.clear();reset();}}/></label><button className="brand-secondary" disabled={loaded.busy||mutations.busy}>Consultar quantidade sem lote</button></form><ReadState task={loaded}/>
 {loaded.data&&<><p className="operation-id">Resultado: {loaded.data.result_id}<br/>Produto: {loaded.data.product_id}</p><p>Produzido: {q(loaded.data.produced_milli)} {loaded.data.unit}. Atribuído: {q(loaded.data.assigned_milli)}. Sem lote: {q(loaded.data.unassigned_milli)}.</p>{loaded.data.unassigned_milli>0?<><label className="brand-field">Quantidade ({loaded.data.unit})<input inputMode="decimal" maxLength={32} disabled={mutations.blocked} value={quantity} onChange={e=>{setQuantity(e.target.value);setConfirm(false);}}/></label><label className="brand-field">Código do lote<input maxLength={64} disabled={mutations.blocked} value={code} onChange={e=>{setCode(e.target.value);setConfirm(false);}}/></label><label className="brand-field">Fabricação declarada<input type="date" disabled={mutations.blocked} value={made} onChange={e=>{setMade(e.target.value);setConfirm(false);}}/></label><label className="brand-field">Validade declarada (opcional)<input type="date" disabled={mutations.blocked} value={expiry} onChange={e=>{setExpiry(e.target.value);setConfirm(false);}}/></label><p>Validade vazia significa desconhecida; não será calculada automaticamente.</p><label className="brand-field">Motivo<textarea maxLength={255} disabled={mutations.blocked} value={reason} onChange={e=>{setReason(e.target.value);setConfirm(false);}}/></label>{error&&<p role="alert">{error}</p>}{measured!==undefined&&<p>Atribuir {q(measured)} {loaded.data.unit} ao código {code.trim()}, com fabricação {made} e validade {expiry||'não informada'}.</p>}<label><input type="checkbox" checked={confirm} disabled={mutations.blocked} onChange={e=>setConfirm(e.target.checked)}/> Conferi os dados e confirmo a declaração.</label><button className="brand-primary" disabled={mutations.blocked||!confirm||measured===undefined} onClick={()=>void save()}>Registrar lote</button></>:<p>Não existe quantidade sem lote neste resultado.</p>}<p>O servidor confere o total disponível ao gravar. Uma recusa não altera os dados nem repete a operação automaticamente.</p></>}
 </ReadSection>;
}
