import { useEffect, useState } from 'react';
import { localClient, localErrorMessage } from '../../../core/local/useLocalSession';
import { formatLocalCents } from '../../../core/local/localClient.mjs';
import type { SaleReceipt, SaleSummary } from '../../../core/local/localClient.mjs';
export default function SalesHistory({token,revision,onRead}:{token:string;revision:number;onRead:(r:SaleReceipt)=>void}) {
 const [rows,setRows]=useState<SaleSummary[]>([]);const [offset,setOffset]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let live=true;setBusy(true);setError('');localClient.history(token,offset).then(v=>{if(live)setRows(v);}).catch(e=>{if(live)setError(localErrorMessage(e));}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[token,offset,revision,refresh]);
 async function read(id:string){if(busy)return;setBusy(true);setError('');try{onRead(await localClient.receipt(token,id));}catch(e){setError(localErrorMessage(e));}finally{setBusy(false);}}
 return <section className="brand-panel pos-history"><div className="brand-panel-top"><div><h2>Histórico de vendas</h2><p>Vendas deste operador neste aparelho · Todos os turnos · Registro não fiscal</p></div><button className="brand-secondary" disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Atualizar histórico</button></div>
 {error && <p role="alert" className="brand-message error">{error}</p>}{busy?<p role="status">Consultando registros…</p>:<div className="brand-table-scroll"><table className="brand-table"><thead><tr><th>Data</th><th>Venda</th><th>Turno</th><th>Situação</th><th>Total</th><th>Consulta</th></tr></thead><tbody>{rows.map(r=><tr key={r.sale_id}><td>{Number.isNaN(Date.parse(r.committed_at))?r.committed_at:new Date(r.committed_at).toLocaleString('pt-BR')}</td><td title={r.sale_id}>{r.sale_id.slice(0,12)}</td><td title={r.cash_session_id}>{r.cash_session_id.slice(0,8)}</td><td>{r.status==='cancelled'?'Cancelada':'Confirmada'}</td><td>{formatLocalCents(r.total_cents)}</td><td><button className="brand-secondary" onClick={()=>void read(r.sale_id)}>Ver registro</button></td></tr>)}</tbody></table>{!rows.length && !error && <p className="brand-state">Nenhuma venda nesta página.</p>}</div>}
 <nav className="brand-pagination" aria-label="Histórico de vendas"><button className="brand-secondary" disabled={busy || offset===0} onClick={()=>setOffset(v=>Math.max(0,v-20))}>Anterior</button><span>Página {offset/20+1}</span><button className="brand-secondary" disabled={busy || rows.length<20} onClick={()=>setOffset(v=>v+20)}>Próxima</button></nav></section>;
}
