import {useState} from 'react';
import {Link} from 'react-router-dom';
import {BrandShell} from '../../../shared/brand/BrandShell';
import './registration.css';
const plans=[
 {id:'pos',name:'PDV e varejo',price:350,previous:0,description:'Frente de caixa e estoque para venda no varejo.'},
 {id:'production',name:'Empresa e produção',price:2500,previous:3500,description:'Planejamento de produção e estoque. PDV é opcional e contratado separadamente.'},
 {id:'staff',name:'Escritório e RH',price:2500,previous:3500,description:'Funcionários, ponto e gestão de pessoas. Acesso depende da autorização da empresa.'},
 {id:'accounting',name:'Contabilidade e contador',price:999,previous:1500,description:'Área contábil separada. Não habilita acesso automático às demais áreas.'},
];
export default function Registration(){
 const [size,setSize]=useState('MEI'),[activity,setActivity]=useState('Varejo'),[storage,setStorage]=useState('Local'),[logins,setLogins]=useState('1'),[selected,setSelected]=useState<string[]>(['pos']),[message,setMessage]=useState('');
 const sum=plans.filter(p=>selected.includes(p.id)).reduce((n,p)=>n+p.price,0);
 function select(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);setMessage('');}
 return <BrandShell footer={false}><section className="registration"><div className="registration-tabs"><Link viewTransition to="/local/login">Entrar</Link><span className="active" aria-current="page">Criar conta</span></div><p className="brand-eyebrow">CADASTRO COMERCIAL</p><h1>Uma configuração para sua empresa</h1><p className="brand-state">Escolha o porte, a atividade e os módulos. O perfil de cada funcionário será definido separadamente pela empresa.</p><form onSubmit={e=>{e.preventDefault();setMessage('Configuração preparada nesta tela. Cadastro comercial, pagamento e emissão da licença ainda não estão conectados; nenhuma conta foi criada ou cobrança realizada.');}}>
 <section className="brand-panel"><h2>Perfil da empresa</h2><div className="catalog-form"><label>Porte / enquadramento<select value={size} onChange={e=>setSize(e.target.value)}>{['MEI','Microempresa','Empresa de pequeno porte','Média empresa','Grande empresa'].map(v=><option key={v}>{v}</option>)}</select></label><label>Atividade principal<select value={activity} onChange={e=>{const value=e.target.value;setActivity(value);setSelected([value==='Varejo'?'pos':value==='Produção / indústria'?'production':value==='Escritório de RH'?'staff':'accounting']);setMessage('');}}>{['Varejo','Produção / indústria','Escritório de RH','Contabilidade / contador'].map(v=><option key={v}>{v}</option>)}</select></label><label>Armazenamento desejado<select value={storage} onChange={e=>setStorage(e.target.value)}>{['Local','Servidor próprio','Nuvem','Híbrido'].map(v=><option key={v}>{v}</option>)}</select></label><label>Quantidade desejada de acessos<input required type="number" min="1" max="10000" value={logins} onChange={e=>setLogins(e.target.value)}/></label></div></section>
 <h2 className="registration-heading">Escolha seus módulos</h2><div className="plan-grid">{plans.map(p=><button type="button" key={p.id} className={`plan-card ${selected.includes(p.id)?'selected':''}`} aria-pressed={selected.includes(p.id)} onClick={()=>select(p.id)}><span className="plan-badge">{selected.includes(p.id)?'Selecionado':'Selecionar módulo'}</span><h3>{p.name}</h3>{p.previous>0 && <p className="plan-previous">De R$ {p.previous.toLocaleString('pt-BR')},00</p>}<p className="plan-price">R$ {p.price.toLocaleString('pt-BR')},00<small>/mês</small></p><p>{p.description}</p></button>)}</div><section className="brand-panel registration-summary"><h2>Sua configuração</h2><p>{size} · {activity} · {storage} · {logins} acesso(s) desejado(s)</p><strong>R$ {sum.toLocaleString('pt-BR')},00 / mês</strong><p className="brand-state">Somatório dos módulos selecionados. Opções de armazenamento e quantidade de acessos ainda não são limites operacionais aprovados.</p><button className="brand-primary" disabled={!selected.length}>Preparar contratação</button>{message && <p role="status" className="brand-message">{message}</p>}</section></form><Link viewTransition className="brand-link" to="/local/login">Voltar ao login</Link></section></BrandShell>;
}
